# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-08 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotator', '0009_auto_20170815_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnnotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('annotation', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=1048)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.AddField(
            model_name='videoannotation',
            name='videoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Video'),
        ),
    ]
